name: 'Create and Save Tag'
description: 'Creates a new tag and saves it'
inputs:
  complete:
    description: 'Whether the pipline is completed'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: tag_name
      id: tag_name
      run: |
        PREFIX=""
        if [ "${{ inputs.complete }}" == "true" ]; then
          PREFIX="release#"
        fi
        TAG_NAME=$PREFIX$(date +'%Y%m%dT%H%M%S')
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
      shell: bash
    - name: Create Tag
      run: |
        TAG_NAME=${{ steps.tag_name.outputs.tag_name }}
        git tag $TAG_NAME
      shell: bash
    - name: Push Tag
      run: |
        TAG_NAME=${{ steps.tag_name.outputs.tag_name }}
        git push origin $TAG_NAME
      shell: bash
